# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-07 20:38
from __future__ import unicode_literals

from django.db import migrations, models
import star_destroyers.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarDestroyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Name')),
                ('capitane', models.CharField(max_length=40, unique=True, verbose_name='Capitan')),
                ('typeof', models.CharField(choices=[('Victory', 'Victory'), ('Emperial', 'Emperial')], max_length=7, verbose_name='Type of star destroyer')),
                ('number_of_people', models.PositiveIntegerField(default=400)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', upload_to=star_destroyers.models.make_upload_path)),
            ],
        ),
    ]
